FROM nginxinc/nginx-unprivileged:1.29.4-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /etc/nginx/html/index.html
COPY styles.css /etc/nginx/html/styles.css
COPY script.js /etc/nginx/html/script.js
